export const DASHBOARD_RELATIVE_PARAMS = "/";
export const MASTER_DATA_RELATIVE_PARAMS = "/master-data";
export const ABSENCE_RELATIVE_PARAMS = "/absence";

export const BANK_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/bank`;
export const SHIFT_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/shift`;
export const DEPARTMENT_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/department`;

export const BANK_CREATE_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/bank/create`;
export const SHIFT_CREATE_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/shift/create`;
export const DEPARTMENT_CREATE_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/department/create`;
export const EMPLOYEE_CREATE_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/employee/create`;

export const DEPARTMENT_DETAIL_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/department/detail`;
export const EMPLOYEE_DETAIL_RELATIVE_PARAMS = `${MASTER_DATA_RELATIVE_PARAMS}/employee/detail`;
